/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sarisaristore;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author zeus
 */
public class ShowMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShowMenu.class.getName());

    /**
     * Creates new form ShowMenu
     */
    
    ArrayList<Cart> myCart = new ArrayList<>();
    ArrayList<Product> drinks;
    ArrayList<Product> snacks;
    ArrayList<Product> product;
    
    public ShowMenu() {
        initComponents();
    }
    
    public ShowMenu(ArrayList<Product> drinks, ArrayList<Product> snacks, ArrayList<Product> product, String category){
        initComponents();
        this.drinks = drinks;
        this.snacks = snacks;
        this.product = product;
        displayAll(product);
        lblCategory.setText("CATEGORY: " + category.toUpperCase());
    }
    
    private void displayAll(ArrayList<Product> product) {
        int index = 1;
        
        String display = "ID\tProduct\tPrice\tStock\n";
        display += "-------------------------------------------------------------------------------\n";
        for(Product p : product) {
            display += index + "\t"  + p.getName() + "\t₱" + p.getPrice() + "\t" + p.getStock() + "pcs left\n";
            index++;
        }
        
        txtareaPrint.setText(display);
    }
    
    public void addToCart(ArrayList<Product> product) {
        int choice = (int) jSpinnerChoice.getValue() - 1 ;
        if (choice <= -1 || choice > product.size() - 1) {
            JOptionPane.showMessageDialog(rootPane,
                    "Invalid input. Please enter a valid choice.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        int quantity = (int) jSpinnerQuantity.getValue();
        Product userChoice = product.get(choice);
        boolean isFound = false;
        
        if (quantity > userChoice.getStock()) {
            JOptionPane.showMessageDialog(rootPane, 
                    "No enough stock. There are " + userChoice.getStock() + "pcs left.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        for (Cart cart : myCart) {
            if (cart.getName().equalsIgnoreCase(userChoice.getName())) {                
                cart.setQuantity(cart.getQuantity() + quantity);
                isFound = true;
                break;
            }
        }
        
        if (!isFound) {
            myCart.add(new Cart(userChoice.getName(), userChoice.getPrice(), quantity));
        }
        
        userChoice.updateStock(userChoice.getStock() - quantity);
        displayAll(product); 
        JOptionPane.showMessageDialog(rootPane, 
                quantity + " " + userChoice.getName() + " added successfully.", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE
        );
    }
    
    public void showCart() {
        String viewCart = "Current Items: \n\n";
        
        if (myCart.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, 
                    "No item here", 
                    "View Cart", 
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        for (Cart cart : myCart) {
            viewCart += cart.getName() + " " + cart.getQuantity() +"pc(s)\n";
        }
        
        JOptionPane.showMessageDialog(rootPane, 
                viewCart, 
                "View Cart", 
                JOptionPane.INFORMATION_MESSAGE
        );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCategory = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaPrint = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnAddToCart = new javax.swing.JButton();
        jSpinnerChoice = new javax.swing.JSpinner();
        jSpinnerQuantity = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        btnViewCart = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        lblCategory.setText("Category:");

        btnBack.setText("back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        txtareaPrint.setEditable(false);
        txtareaPrint.setColumns(20);
        txtareaPrint.setRows(5);
        jScrollPane1.setViewportView(txtareaPrint);

        jLabel1.setText("Enter ID choice: ");

        btnAddToCart.setBackground(new java.awt.Color(255, 153, 102));
        btnAddToCart.setText("add to cart");
        btnAddToCart.addActionListener(this::btnAddToCartActionPerformed);

        jSpinnerQuantity.setValue(1);

        jLabel2.setText("Enter quantity:");

        btnViewCart.setBackground(new java.awt.Color(255, 255, 153));
        btnViewCart.setText("view cart");
        btnViewCart.addActionListener(this::btnViewCartActionPerformed);

        btnPayment.setBackground(new java.awt.Color(153, 255, 153));
        btnPayment.setText("payment");
        btnPayment.addActionListener(this::btnPaymentActionPerformed);

        btnExit.setText("Exit");
        btnExit.addActionListener(this::btnExitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(lblCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerChoice)
                            .addComponent(jSpinnerQuantity)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnViewCart, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddToCart)))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinnerChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewCart)
                    .addComponent(btnAddToCart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPayment)
                    .addComponent(btnExit))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainStore mainStore = new MainStore(drinks, snacks);
        mainStore.setLocationRelativeTo(null);
        mainStore.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        addToCart(product);
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnViewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCartActionPerformed
        // TODO add your handling code here:
        showCart();
    }//GEN-LAST:event_btnViewCartActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        // TODO add your handling code here:
        if (myCart.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, 
                    "YOu didn't pick anything", 
                    "Payment Error", 
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        Payment payment = new Payment(drinks, snacks, myCart);
        payment.setLocationRelativeTo(null);
        payment.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new ShowMenu().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnViewCart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerChoice;
    private javax.swing.JSpinner jSpinnerQuantity;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JTextArea txtareaPrint;
    // End of variables declaration//GEN-END:variables
}
